name: Release Workflow

on:
  release:
    types: [created]

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run build script
      run: |
        chmod +x Tools/build.sh
        ./Tools/build.sh ${{ github.event.release.tag_name }}

    - name: Upload artifact
      run: |
        gh release upload ${{github.event.release.tag_name}} Systemless-DeGoogler-${{ github.event.release.tag_name }}.zip